### ISSUE TITLE
Roadmap after _libnfs_

### ISSUE THREAD

**Issue by masterzorag** [orbisdev/liborbis#41]
Since from the beginning a lot of stuff are done, this issue is to track and show next tasks to be worked out to consolidate the library.

# host access
ps4link/ps4sh was the initial way and some libraries depend on that, but then comes _libnfs_:
- [ ] provide a preprocessor to those libraries to build with one or the other
- [ ] track down dependencies 
- [ ] goal is park old way and migrate to _libnfs_
- [ ] links to some _libnfs_ server setup to get a valid host environment or a dedicated issue
- [ ] review readme
- [ ] loader change: even if source are public (link) no one seems using
